'use strict'
const {test}=require('node:test')
const assert=require('node:assert/strict')
const day=require('./day')
const add=(s,extra={},by='agent')=>day.act(s,{action:'add',title:'Review billing PR',source:'github',...extra},by).item
test('items from different sources that share a link merge into one',()=>{
  const s={}
  const pr=add(s,{links:['https://github.com/acme/api/pull/42']})
  const again=day.act(s,{action:'add',title:'Thread about PR 42',source:'slack',links:['https://github.com/acme/api/pull/42/?utm=x','https://acme.slack.com/archives/C1/p1'],context:'Anna asks for a review today.'})
  assert.equal(again.merged,true)
  assert.equal(again.item.id,pr.id)
  assert.equal(s.dayBoard.items.length,1)
  assert.equal(pr.links.length,3)
  assert.match(pr.context,/Anna/)
  assert.equal(day.act(s,{action:'add',title:'Other',source:'linear',links:['https://linear.app/a/issue/TECH-1']}).merged,false)
})
test('the agent proposes; only the operator triages, and their own items start on today',()=>{
  const s={},proposed=add(s)
  assert.equal(proposed.status,'proposed')
  assert.throws(()=>day.act(s,{action:'update',itemId:proposed.id,status:'today'}),/triaged by the operator/)
  day.act(s,{action:'update',itemId:proposed.id,status:'dropped'})
  assert.equal(proposed.status,'dropped')
  day.triage(s,proposed.id,{status:'today',priority:'must',mode:'draft'})
  assert.deepEqual([proposed.status,proposed.priority,proposed.mode],['today','must','draft'])
  assert.equal(add(s,{title:'Call the accountant',source:'me'},'operator').status,'today')
})
test('a question parks only its item, and answering hands the item back once',()=>{
  const s={},a=add(s,{},'operator'),b=add(s,{title:'Reply to Marc',source:'slack'},'operator')
  assert.throws(()=>day.act(s,{action:'update',itemId:a.id,status:'waiting_on_you'}),/open question/)
  const need=day.act(s,{action:'ask',itemId:a.id,kind:'choose',question:'Approve or request changes?',options:['approve','request changes']})
  assert.equal(a.status,'waiting_on_you')
  assert.equal(b.status,'today','other items keep moving')
  assert.equal(day.waiting(s).length,1)
  assert.throws(()=>day.answer(s,a.id,need.id,'maybe'),/offered options/)
  day.answer(s,a.id,need.id,'approve')
  assert.equal(a.status,'in_progress')
  assert.equal(day.waiting(s).length,0)
  assert.throws(()=>day.answer(s,a.id,need.id,'approve'),/already answered/)
  const first=day.act(s,{action:'list'}).items.find(i=>i.id===a.id)
  assert.deepEqual(first.answered.map(x=>x.answer),['approve'])
  const second=day.act(s,{action:'list'}).items.find(i=>i.id===a.id)
  assert.deepEqual(second.answered,[],'an answer is delivered to the agent once')
})
test('the operator reading the board does not consume answers meant for the agent',()=>{
  const s={},a=add(s,{},'operator'),need=day.act(s,{action:'ask',itemId:a.id,kind:'info',question:'Which env?'})
  day.answer(s,a.id,need.id,'staging')
  day.act(s,{action:'list'},'operator')
  assert.equal(day.act(s,{action:'list'}).items[0].answered.length,1)
})
test('an approval carries its exact draft and blocks done until decided',()=>{
  const s={},a=add(s,{},'operator')
  assert.throws(()=>day.act(s,{action:'ask',itemId:a.id,kind:'approve',question:'Send this?'}),/exact draft/)
  const need=day.act(s,{action:'ask',itemId:a.id,kind:'approve',question:'Send this reply to Marc?',draft:'Looks good, merging after lunch.'})
  assert.throws(()=>day.act(s,{action:'update',itemId:a.id,status:'done'}),/unanswered approval/)
  day.answer(s,a.id,need.id,'approve')
  day.act(s,{action:'update',itemId:a.id,status:'done',note:'Sent the reply.'})
  assert.equal(a.status,'done')
  assert.equal(a.log.at(-1).text,'Sent the reply.')
})
test('list stays compact and hides settled items unless asked',()=>{
  const s={},a=add(s,{context:'x'.repeat(5000)},'operator');add(s,{title:'Done thing',source:'me'},'operator')
  day.act(s,{action:'update',itemId:s.dayBoard.items[1].id,status:'done'})
  const list=day.act(s,{action:'list'})
  assert.equal(list.items.length,1)
  assert.equal(list.closed,1)
  assert.equal(list.items[0].context,undefined,'context is read with inspect, not on every list')
  assert.equal(day.act(s,{action:'inspect',itemId:a.id}).context.length,5000)
  assert.equal(day.act(s,{action:'list',includeClosed:true}).items.length,2)
})
test('cursors record per-source progress and reject unknown sources',()=>{
  const s={}
  assert.deepEqual(day.act(s,{action:'cursor',source:'slack'}),{source:'slack',value:null})
  day.act(s,{action:'cursor',source:'slack',value:'1727771100.000100'})
  assert.equal(day.act(s,{action:'cursor',source:'slack'}).value,'1727771100.000100')
  assert.throws(()=>day.act(s,{action:'cursor',source:'me'}),/Source/)
})
test('a new day carries unfinished work and its open questions, and drops what was settled',()=>{
  const s={},keep=add(s,{},'operator'),done=add(s,{title:'Done',source:'me'},'operator'),proposed=add(s,{title:'Untriaged',source:'slack'})
  day.act(s,{action:'ask',itemId:keep.id,kind:'info',question:'Which customer?'})
  day.act(s,{action:'update',itemId:done.id,status:'done'})
  day.act(s,{action:'cursor',source:'linear',value:'2026-09-30T18:00:00Z'})
  const next=day.carryOver(s.dayBoard,'2026-10-02')
  assert.equal(next.date,'2026-10-02')
  assert.deepEqual(next.items.map(i=>i.id),[keep.id])
  assert.equal(next.items[0].status,'waiting_on_you')
  assert.equal(next.items[0].carriedFrom,s.dayBoard.date)
  assert.equal(next.cursors.linear,'2026-09-30T18:00:00Z')
  assert.ok(!next.items.some(i=>i.id===proposed.id))
})
test('progress counts triaged work and what is waiting on the operator',()=>{
  const s={},a=add(s,{},'operator');add(s)
  day.act(s,{action:'ask',itemId:a.id,kind:'info',question:'?'})
  assert.deepEqual(day.progress(s),{total:1,done:0,proposed:1,waiting:1})
  assert.equal(day.progress({}),null)
})
